### ISSUE TITLE
Import to app button failure

### ISSUE THREAD

**Issue by Ashaxer** [MuhammadAshouri/marzban-templates#12]
I've been facing this issue since the start.
when I use 'Import to app' button, the domain part in the link it tries to load is missing.
something like this:
streisand://install-config?url=/sub/VGVjaG5vMTg3NiwxNzI4MjM1MDkx
![image](https://github.com/user-attachments/assets/28bca774-49ee-401a-8f3f-ad8872bf8397)

I've tried adding my domain text aside my domain at the start of 'autoImport' key in the index.html file but I ended up having duplicated domains like this:
streisand://install-config?url=https://example.comhttps://example.com/sub/VGVjaG5vMTg3NiwxNzI4MjM1MDkx

**Comment by MuhammadAshouri** [comment]
You just need to set XRAY_SUBSCRIPTION_URL_PREFIX variable in marzban's .env file

**Comment by Ashaxer** [comment]
Thanks! It is fixed now
