### ISSUE TITLE
Copy buttons do not work

### ISSUE THREAD

**Issue by OwnerLink** [MuhammadAshouri/marzban-templates#3]
this question has been asked before, and I saw the answer about ssl.
But is it possible to make copying possible without it? Since I have problems with them that I can't solve. And what the problem is I haven't understood yet.

**Comment by MuhammadAshouri** [comment]
It's browsers' limitations. I'll look into it

**Comment by OwnerLink** [comment]
> It's browsers' limitations. I'll look into it

Thank you :) I'll be looking forward to it. Just the standard panel works without ssl, hope you can solve this problem.

**Comment by nimabark** [comment]
How can I use it for the Sanaie panel?

**Comment by OwnerLink** [comment]
Anyway, I solved the ssl problem and the button worked. But if you have already started researching ways of copying without ssl then please continue, not everyone needs this ssl :)
Me for example, but the button made it work lol :D

Should I close this thread?
